cmake_minimum_required(VERSION 4.0)
project(Lab04_2026_1_20242165_Dominguez_Joseph)

set(CMAKE_CXX_STANDARD 20)

add_executable(Lab04_2026_1_20242165_Dominguez_Joseph main.cpp
        Biblioteca/BibliotecaGenerica.cpp
        Biblioteca/BibliotecaGenerica.h
        Biblioteca/BibliotecaRegistros.cpp
        Biblioteca/BibliotecaRegistros.h
        Biblioteca/BibliotecaEnteros.cpp
        Biblioteca/BibliotecaEnteros.h)
